staging:
  profile: ~
  whoami: 2.x-site-stg-out
  subdir: content/log4j/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 2799
# - Commit ID: fb9b6269038e2e0673108d1ab8ec6ca9947efc4b
# - Timestamp: 2024-07-08T18:32:04Z
