staging:
  profile: ~
  whoami: 2.x-site-stg-out
  subdir: content/log4j/2.x


# INFRA cannot handle change sets bigger than a certain size: https://the-asf.slack.com/archives/CBX4TSBQ8/p1709724983391709
# This file will be used to push a small commit to help the INFRA to recover.
#
# Random values to cause a change:
#
# - Seed: 11970
# - Commit ID: badb28cfe0e7e02ca56170eab6f0d2afb35bbb6d
# - Timestamp: 2024-05-01T08:48:57Z
